### ISSUE TITLE
 'DesktopId' property must be set

### ISSUE THREAD

**Issue by LeoIannacone** [parinporecha/GeoClue2-Locator-python#1]
Hi,

great example!.. but I'm having this issue:

```
This code will print your location and exit after 10 seconds
Traceback (most recent call last):
  File "where-am-i.py", line 169, in <module>
    main()
  File "where-am-i.py", line 158, in main
    client.Start()
  File "/usr/lib/python2.7/dist-packages/dbus/proxies.py", line 145, in __call__
    **keywords)
  File "/usr/lib/python2.7/dist-packages/dbus/connection.py", line 651, in call_blocking
    message, timeout)
dbus.exceptions.DBusException: org.freedesktop.DBus.Error.AccessDenied: 'DesktopId' property must be set
```

**Comment by parinporecha** [comment]
Hi @LeoIannacone , thanks !

When I'd written this script in Nov '13, GeoClue API didn't have this property. The newer version asks applications to set the [DesktopId](http://www.freedesktop.org/software/geoclue/docs/gdbus-org.freedesktop.GeoClue2.Client.html#gdbus-property-org-freedesktop-GeoClue2-Client.DesktopId) for authorization.

Adding support for this will require trivial changes. I'm happy to accept patches :-)

**Comment by LeoIannacone** [comment]
Right now I'm a beginner of GeoClue ... So, I think I can't be very helpful. If you fix it I will use your example in my app.

Thanks @parinporecha

**Comment by thilomaurer** [comment]
Same here

**Comment by mburucuyapy** [comment]
Im a bit late here, but has anyone fixed this?
